default_deploy_mode = "upload"

[build]
# options to allow building code against rust versions >=1.70 without opcodes
# incompatible with screeps server environments; requires nightly rust. See 
# https://github.com/rustyscreeps/screeps-game-api/issues/391
extra_options = ["--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort"]

[upload]
auth_token = "your screeps.com auth token"

[ptr]
auth_token = "your screeps.com auth token"
prefix = "ptr"

[copy]
destination = "path to your local code directory from your game client, without branch directory"
[copy.build]
  # set the sim feature to allow for use with the coordinates in the simulation room
  extra_options = ["--features=sim", "--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort"]

[season]
auth_token = "your screeps.com auth token"
prefix = "season"
  [season.build]
  extra_options = ["--features=my-crate-season-1-feature", "--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort"]

# for full syntax and available options, see
# https://github.com/rustyscreeps/screeps-game-api/blob/master/screeps-defaults.toml
